# A unique identifier for the head node and workers of this cluster.
cluster_name: minimal

# Cloud-provider specific configuration.
provider:
    type: gcp
    region: us-west1
    project_id: divine-beanbag-406919
    availability_zone: us-west1-c,us-west1-b